# k8s/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sd2025-project
  namespace: argocd
spec:
  project: grupo6
  source:
    repoURL: 'https://github.com/LeandroSybilla/sd2025-project.git'
    targetRevision: kub-update
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grupo6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
