apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: leandrosybilla/sd2526-backend:6e1ce8865030d68d37d4408099d8b4571abcdbb6
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        - name: RABBIT_VHOST
          value: "grupo6"
        ports:
        - containerPort: 8000
