apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: leandrosybilla/sd2526-backend:062ffc68cc9054f6715f75bef84a43d6dcbfee5b
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        ports:
        - containerPort: 8000
