apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: grupo6
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - grupo6
  endpoints:
  - port: metrics # Assuming the service has a port named 'metrics' or use targetPort if number
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simulator-monitor
  namespace: grupo6
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: simulator
  namespaceSelector:
    matchNames:
      - grupo6
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s