apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator-default
        # image: leandrosybilla/sd2526-simulator:895c7a475db118a34a9749ff68fc186ebfcc822b
        image: local/simulator
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "default"

      - name: simulator-madeira-crossing
        # image: leandrosybilla/sd2526-simulator:895c7a475db118a34a9749ff68fc186ebfcc822b
        image: local/simulator
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "madeira_crossing"

      - name: simulator-pr9
        # image: leandrosybilla/sd2526-simulator:895c7a475db118a34a9749ff68fc186ebfcc822b
        image: local/simulator
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "pr9"

      - name: simulator-pr13
        # image: leandrosybilla/sd2526-simulator:895c7a475db118a34a9749ff68fc186ebfcc822b
        image: local/simulator
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "pr13"