apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: simulator
        image: leandrosybilla/sd2526-simulator:4ee0345992032879fa5aca20a2222b3dd22ae7fc
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        - name: RABBIT_VHOST
          value: "grupo6"
        - name: TRAIL_ID
          value: "grupo6_default"

      - name: simulator-madeira-crossing
        image: leandrosybilla/sd2526-simulator:4ee0345992032879fa5aca20a2222b3dd22ae7fc
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        - name: RABBIT_VHOST
          value: "grupo6"
        - name: TRAIL_ID
          value: "grupo6_madeira_crossing"

      - name: simulator-pr9
        image: leandrosybilla/sd2526-simulator:4ee0345992032879fa5aca20a2222b3dd22ae7fc
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        - name: RABBIT_VHOST
          value: "grupo6"
        - name: TRAIL_ID
          value: "grupo6_pr9"

      - name: simulator-pr13
        image: leandrosybilla/sd2526-simulator:4ee0345992032879fa5aca20a2222b3dd22ae7fc
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"
        - name: RABBIT_VHOST
          value: "grupo6"
        - name: TRAIL_ID
          value: "grupo6_pr13"
