apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: simulator
        image: leandrosybilla/sd2526-simulator:c9e44ec100ab1f57b17d37f9ed27c62dd2824fa8
        env:
        - name: RABBIT_URL
          value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "default"

      - name: simulator-madeira-crossing
        image: leandrosybilla/sd2526-simulator:c9e44ec100ab1f57b17d37f9ed27c62dd2824fa8
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "madeira_crossing"

      - name: simulator-pr9
        image: leandrosybilla/sd2526-simulator:c9e44ec100ab1f57b17d37f9ed27c62dd2824fa8
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "pr9"

      - name: simulator-pr13
        image: leandrosybilla/sd2526-simulator:c9e44ec100ab1f57b17d37f9ed27c62dd2824fa8
        env:
        - name: RABBIT_URL
          value: "10.96.238.249"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "default_user_CcJpclM0MAy-WQXf1f1"
        - name: RABBIT_PASS
          value: "iWR6qS0N2jLQGkdBVYl1FwePHoPAjIjw"
        - name: TRAIL_ID
          value: "pr13"
