apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  namespace: grupo-6
  labels:
    app: simulator
spec:
  selector:
    app: simulator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
