apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  labels:
    app: simulator
spec:
  selector:
    app: simulator
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http-metrics
  type: ClusterIP
