apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: leandrosybilla/sd2526-simulator:d93efcff3015e4ff7d0c50bdcb7dad7176c589f0
        env:
        - name: RABBIT_URL
          value: "rabbitmq"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"