apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  namespace: grupo6
  labels:
    app: simulator
spec:
  selector:
    app: simulator
  ports:
  - protocol: TCP
    port: 30046
    targetPort: 8000
    name: metrics
  type: LoadBalancer
