apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: grupo6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: leandrosybilla/sd2526-simulator:bb64d58906a8e02b57c144c72195259e607afbb9
        env:
        - name: RABBIT_URL
          value: "rabbitmq.10.2.15.161.nip.io"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: "grupo6"
        - name: RABBIT_PASS
          value: "x2c3v4b5n6m7"